server:
  port: 8999
spring:
  application:
    name: eureka-producer
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.107.246.54:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 118756
      hikari:
        minimum-idle: 5
        idle-timeout: 600000
        maximum-pool-size: 10
        auto-commit: true
        pool-name: MyHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  redis:
    host: 47.107.246.54
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:9999/eureka/,http://localhost:9998/eureka/,http://localhost:9997/eureka/
    # 从Eureka中获取注册信息的间隔时间(默认30)
    registry-fetch-interval-seconds: 10
    eureka-service-url-poll-interval-seconds: 300 # 刷新Eureka服务端地址的间隔时间 默认300秒
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10 # 心跳续约间隔时间(默认30秒)
    lease-renewal-interval-in-seconds: 30 # 心跳超时时间 超时后服务端会剔除该服务(默认90秒)
mybatis:
  type-aliases-package: com.xz.springcloud.domain
  mapper-locations: mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  server:
    port: 9999

