spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 多数据源时 配置 jdbc-url 单数据源使用会报错
    url: jdbc:mysql://47.107.246.54:3306/blog_resource?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 118756
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
server:
  port: 8081
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.xz.oauth.resource.domain
security:
  oauth2:
#    client: # 远程认证服务器时所需
#      client-id: client   # 必须和认证服务器中的匹配 否则等于并不是所属业务发起的请求
#      client-secret: secret
#      access-token-uri: http://localhost:8080/oauth/token # 认证服务器获取token 地址
#      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource: # 这个地址需要认证服务器授权(配置开放)
      # token-info-uri: http://localhost:8080/oauth/check_token
      jwt: # 密钥 Cannot convert access token to JSON
        key-value: test
